### ISSUE TITLE
Consuming quiz

### ISSUE THREAD

**Issue by kevinand11** [stranerd/sofa-web-frontend#13]
- [x] When previewing the quiz, remove the progress counter at the top. No need since it shows at the bottom. Replace with “Quiz preview” text to indicate you are previewing. For regular quiz use, the counter at the top should be slideable, so that I can drag it and go directly to a question ✅
- [x] At the final question, pressing prev takes me back to the first instead of the one before. Also, disable prev and next if I can’t go back or forward anymore  ✅
- [ ] Multichoice: question with more than one correct answer doesn’t allow me to select more than one.
I have a question with 6 options and 2 correct answers. Any time I click option 5 or 6, it selects both options 5 and 6. Fix that. Apart from this weird behavior, it doesn’t allow me ever have 2 options selected.
For a question with more than 1 correct answer, for eg 2 correct answers, if I have already selected 2 answers and I select another one, wipe out all that I have selected before and add the recently selected one ❌
- [x] drag answers: I can’t drag an option into a slot, it doesn’t land. I can’t test this but if I drop an option into a slot, the option shouldn’t appear in the list of options below anymore  ✅
- [x] write answer: input should be a text box, and remove the check/circle icon  ✅
- [ ] match: the icons of the question and the correct answer always match, so that is always an indicator to the user about the correct answers. Let the answers' shape use the index to determine which one to show so that the question and answer next to each other at any time have the same shape, whether correct or not  ❌
- [x] in practice mode, show correct answer and explanation when in check ✅

**Comment by Doctordrayfocus** [comment]
"match: the icons of the question and the correct answer always match, so that is always an indicator to the user about the correct answers. Let the answers' shape use the index to determine which one to show so that the question and answer next to each other at any time have the same shape, whether correct or not"

At the initial state, I can maintain the same icon per row, but once the sorting starts, it is impossible to maintain same icon based on the  index.

**Comment by Doctordrayfocus** [comment]
"Multichoice: question with more than one correct answer doesn’t allow me to select more than one.
I have a question with 6 options and 2 correct answers. Any time I click option 5 or 6, it selects both options 5 and 6. Fix that. Apart from this weird behavior, it doesn’t allow me ever have 2 options selected.
For a question with more than 1 correct answer, for eg 2 correct answers, if I have already selected 2 answers and I select another one, wipe out all that I have selected before and add the recently selected one"


If two options in a quiz are similar, selecting one will select the other one, because the only thing unique to an option is it content.
